{
 "title": "Yottadb",
 "time": { "from": "2021-05-13T13:19:19.118Z", "to": "2021-05-13T13:21:54.213Z" },
 "panels": [
  {
   "title": "Global Orders",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ORD" }
   ]
  },
  {
   "title": "Global Sets",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "SET" }
   ]
  },
  {
   "title": "Global Gets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "GET" }
   ]
  }
 ]
}